# Generated by Django 3.0.7 on 2023-01-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shoes', 'shoes'), ('tshirt', 'tshirt'), ('shirt', 'shirt'), ('pant', 'pant'), ('cap', 'cap')], max_length=20)),
                ('selling_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='static/img/product')),
            ],
        ),
    ]
