# Generated by Django 3.0.7 on 2023-01-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230101_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('Used', 'Used'), ('Fresh', 'Fresh')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('spotwear', 'spotwear'), ('shirt', 'shirt'), ('outwear', 'outwear')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='static/img/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
